#!/bin/bash
# Quick visual guide for Upstash setup

echo "🚀 Upstash Redis Quick Setup Guide"
echo "===================================="
echo ""
echo "📋 STEP 1: Open your browser and go to:"
echo "   👉 https://upstash.com"
echo ""
echo "📋 STEP 2: Sign up (free account)"
echo "   - Click 'Sign Up' (top right)"
echo "   - Use GitHub or email"
echo ""
echo "📋 STEP 3: Create Redis Database"
echo "   - Click 'Create Database'"
echo "   - Name: vpoliteiadis-rate-limit"
echo "   - Region: Choose closest to your Vercel deployment"
echo "   - Click 'Create'"
echo ""
echo "📋 STEP 4: Copy Credentials"
echo "   - Click on your database"
echo "   - Copy 'REST URL' (looks like https://xxxxx.upstash.io)"
echo "   - Copy 'REST Token' (long string starting with AX...)"
echo ""
echo "📋 STEP 5: Come back here and run:"
echo "   ./scripts/add-upstash-env-interactive.sh"
echo ""
echo "Then paste your credentials when prompted!"
echo ""
read -p "Press Enter when you've completed steps 1-4..."
